# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kissan',
            name='K_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
