# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0004_auto_20170913_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='kissan',
            name='HLat',
            field=models.FloatField(default=18.347878),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kissan',
            name='HLong',
            field=models.FloatField(default=84.687579),
            preserve_default=False,
        ),
    ]
