# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0005_auto_20170915_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Id', models.IntegerField()),
                ('HLat', models.FloatField()),
                ('HLong', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kissan',
            name='HLat',
        ),
        migrations.RemoveField(
            model_name='kissan',
            name='HLong',
        ),
        migrations.AddField(
            model_name='house',
            name='F_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaikissan.Kissan'),
        ),
    ]
