# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0006_auto_20170915_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kissan',
            name='Phone',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code=b'Invalid number', message=b'Length has to be 10', regex=b'^\\d{10}$')]),
        ),
    ]
