# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0007_auto_20170915_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='Investment',
            field=models.IntegerField(default=12000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='Profit',
            field=models.IntegerField(default=6000),
            preserve_default=False,
        ),
    ]
