# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0008_auto_20171007_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='H_pic',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='Photo',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='Farm_pic',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='kissan',
            name='Profile_pic',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='well',
            name='Well_pic',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='wellupdate',
            name='Wellupadte_pic',
            field=models.ImageField(default=b'media/None/no-img.jpg', upload_to=b'media/'),
        ),
    ]
