# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaikissan', '0009_auto_20171103_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='kissan',
            name='Email',
            field=models.CharField(default='aravindjeripothula@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
